"""Check the distributable allowlist, provenance hashes and Python syntax."""
import ast
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOP_DIRS = {".github", "configs", "data", "docs", "experiments", "provenance", "results", "scripts", "src", "tests"}
SUFFIXES = {".py", ".json", ".csv", ".md", ".toml", ".txt", ".cff", ".yaml", ".yml", ".npz", ".png"}
SPECIAL_FILES = {".gitignore", ".gitattributes", "LICENSE", "NOTICE", "MANIFEST.in"}
ARRAYS = {"configs/paper/center_bias.npz", "configs/paper/std_prior.npz"}


def release_files(root=ROOT):
    files = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(root)
        if rel.as_posix() == "RELEASE_MANIFEST.json":
            continue  # Regenerated by the packer; never include a stale/duplicate manifest.
        if len(rel.parts) > 1 and rel.parts[0] not in TOP_DIRS:
            continue
        if any(part in {"__pycache__", ".pytest_cache"} or part.endswith(".egg-info")
               for part in rel.parts):
            continue
        if path.suffix not in SUFFIXES and path.name not in SPECIAL_FILES:
            continue
        if rel.parts[0] == "data" and rel.as_posix() != "data/README.md":
            raise ValueError(f"Raw data are not allowed in this release: {rel}")
        if path.suffix == ".npz" and rel.as_posix() not in ARRAYS:
            raise ValueError(f"Unapproved array: {rel}")
        if path.is_symlink():
            raise ValueError(f"Symlink in release: {rel}")
        files.append(path)
    return sorted(files)


def check(root=ROOT):
    manifest = json.loads((root / "provenance/source_manifest.json").read_text(encoding="utf-8"))
    for item in manifest["files"]:
        path = root / item["destination"]
        if hashlib.sha256(path.read_bytes()).hexdigest() != item["export_sha256"]:
            raise ValueError(f"Export changed without provenance update: {item['destination']}")
    files = release_files(root)
    for path in files:
        if path.suffix in {".npz", ".png"}:
            continue
        text = path.read_text(encoding="utf-8")
        if path.suffix == ".py":
            ast.parse(text, filename=str(path))
        if path.suffix == ".json":
            json.loads(text)
        if re.search(r"[A-Za-z]:[\\/](?:Users|Project)[\\/]", text):
            raise ValueError(f"Machine-specific absolute path: {path.relative_to(root)}")
        # This is a narrow local scan, not a substitute for hosted secret scanning.
        if re.search(r"-----BEGIN (?:RSA |OPENSSH |EC )?PRIVATE KEY-----", text):
            raise ValueError(f"Private key: {path.relative_to(root)}")
    return {"status": "pass", "release_files": len(files), "export_hashes": len(manifest["files"]),
            "bytes": sum(path.stat().st_size for path in files)}


if __name__ == "__main__":
    print(json.dumps(check(), indent=2))
